# Generated by Django 3.2 on 2021-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_register_newauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='newauth',
            name='field',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
    ]
